"""Add missing columns to messages table

Revision ID: 002
Revises: 001
Create Date: 2025-09-21 23:33:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid

# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add missing columns to messages table
    op.add_column('messages', sa.Column('is_pinned', sa.Boolean(), nullable=True, default=False))
    op.add_column('messages', sa.Column('is_favorite', sa.Boolean(), nullable=True, default=False))
    op.add_column('messages', sa.Column('reactions', sa.JSON(), nullable=True, default=dict))
    op.add_column('messages', sa.Column('forwarded_from_id', postgresql.UUID(as_uuid=True), nullable=True))
    
    # Add foreign key constraint for forwarded_from_id
    op.create_foreign_key('fk_messages_forwarded_from_id', 'messages', 'messages', ['forwarded_from_id'], ['id'], ondelete='SET NULL')
    
    # Set default values for existing rows
    op.execute("UPDATE messages SET is_pinned = FALSE WHERE is_pinned IS NULL")
    op.execute("UPDATE messages SET is_favorite = FALSE WHERE is_favorite IS NULL")
    op.execute("UPDATE messages SET reactions = '{}' WHERE reactions IS NULL")
    
    # Make columns non-nullable after setting defaults
    op.alter_column('messages', 'is_pinned', nullable=False)
    op.alter_column('messages', 'is_favorite', nullable=False)
    op.alter_column('messages', 'reactions', nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove foreign key constraint first
    op.drop_constraint('fk_messages_forwarded_from_id', 'messages', type_='foreignkey')
    
    # Drop columns
    op.drop_column('messages', 'forwarded_from_id')
    op.drop_column('messages', 'reactions')
    op.drop_column('messages', 'is_favorite')
    op.drop_column('messages', 'is_pinned')
    
    # ### end Alembic commands ###