"""Add notification settings table

Revision ID: 002
Revises: 001
Create Date: 2025-09-05 21:41:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid

# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create notification_settings table
    op.create_table('notification_settings',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_project_updates', sa.Boolean(), nullable=True),
    sa.Column('email_messages', sa.Boolean(), nullable=True),
    sa.Column('email_application_status', sa.Boolean(), nullable=True),
    sa.Column('email_payment_updates', sa.Boolean(), nullable=True),
    sa.Column('email_newsletter', sa.Boolean(), nullable=True),
    sa.Column('in_app_project_updates', sa.Boolean(), nullable=True),
    sa.Column('in_app_messages', sa.Boolean(), nullable=True),
    sa.Column('in_app_application_status', sa.Boolean(), nullable=True),
    sa.Column('in_app_payment_updates', sa.Boolean(), nullable=True),
    sa.Column('push_project_updates', sa.Boolean(), nullable=True),
    sa.Column('push_messages', sa.Boolean(), nullable=True),
    sa.Column('push_application_status', sa.Boolean(), nullable=True),
    sa.Column('push_payment_updates', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_settings_id'), 'notification_settings', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_settings_id'), table_name='notification_settings')
    op.drop_table('notification_settings')
    # ### end Alembic commands ###